<a href="https://colab.research.google.com/github/Cyber-Dust/DSCI250/blob/main/EDAmdc22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INITIAL EDA ON NETFLIX DATASET using xplore

In [ ]:
import seaborn as sns
directors = (19,8,16,16,14,13,12,12,12)
sns.lineplot(data=directors, x=year, y=passengers)

ValueError: ignored

In [ ]:
! pip install xplore

from xplore.data import xplore

import pandas as pd

data = pd.read_csv('disney_plus_titles.csv')

In [ ]:
! pip install xplore

from xplore.data import xplore

import pandas as pd

data = pd.read_csv('netflix_titles.csv')


# install all dataframes and assign each data set a name


xplore(data)

Collecting xplore
  Downloading xplore-0.0.1.tar.gz (5.2 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from xplore) (1.3.5)
Requirement already satisfied: pandas_profiling in /usr/local/lib/python3.7/dist-packages (from xplore) (1.4.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->xplore) (2018.9)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->xplore) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->xplore) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->xplore) (1.15.0)
Requirement already satisfied: matplotlib>=1.4 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling->xplore) (3.2.2)
Requirement already satisfied: jinja2>=2.8 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling->xplore) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.8->pandas_profiling->xplore) (2.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.4->pandas_profiling->xplore) (3.0.8)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.4->pandas_profiling->xplore) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.4->pandas_profiling->xplore) (0.11.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=1.4->pandas_profiling->xplore) (4.1.1)
Building wheels for collected packages: xplore
  Building wheel for xplore (setup.py) ... done
  Created wheel for xplore: filename=xplore-0.0.1-py3-none-any.whl size=4195 sha256=ec00eb466a1366d8499d44ee5a20d7e76aa1814dccea2ae8e48d7a1b9046882f
  Stored in directory: /root/.cache/pip/wheels/8f/ee/9f/dc64edd7cbc7d72291f309afa83bcb8258ada61b2445a7b2cf
Successfully built xplore
Installing collected packages: xplore
Successfully installed xplore-0.0.1
------------------------------------
The fist 5 entries of your dataset are:

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...


------------------------------------
The last 5 entries of your dataset are:

     show_id     type        title         director  \
8802   s8803    Movie       Zodiac    David Fincher
8803   s8804  TV Show  Zombie Dumb              NaN
8804   s8805    Movie   Zombieland  Ruben Fleischer
8805   s8806    Movie         Zoom     Peter Hewitt
8806   s8807    Movie       Zubaan      Mozez Singh

                                                   cast        country  \
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

             date_added  release_year rating   duration  \
8802  November 20, 2019          2007      R    158 min
8803       July 1, 2019          2018  TV-Y7  2 Seasons
8804   November 1, 2019          2009      R     88 min
8805   January 11, 2020          2006     PG     88 min
8806      March 2, 2019          2015  TV-14    111 min

                                           listed_in  \
8802                  Cult Movies, Dramas, Thrillers
8803          Kids' TV, Korean TV Shows, TV Comedies
8804                         Comedies, Horror Movies
8805              Children & Family Movies, Comedies
8806  Dramas, International Movies, Music & Musicals

                                            description
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...


------------------------------------
Stats on your dataset:

<bound method NDFrame.describe of      show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]>


------------------------------------
The Value types of each column are:

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object


------------------------------------
Info on your Dataset:

<bound method DataFrame.info of      show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]>


------------------------------------
The shape of your dataset in the order of rows and columns is:

(8807, 12)


------------------------------------
The features of your dataset are:

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')


------------------------------------
The total number of null values from individual columns of your data set are:

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64


------------------------------------
The number of rows in your dataset are:

8807


------------------------------------
The values in your dataset are:

[['s1' 'Movie' 'Dick Johnson Is Dead' ... '90 min' 'Documentaries'
  'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.']
 ['s2' 'TV Show' 'Blood & Water' ... '2 Seasons'
  'International TV Shows, TV Dramas, TV Mysteries'
  'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.']
 ['s3' 'TV Show' 'Ganglands' ... '1 Season'
  'Crime TV Shows, International TV Shows, TV Action & Adventure'
  'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.']
 ...
 ['s8805' 'Movie' 'Zombieland' ... '88 min' 'Comedies, Horror Movies'
  'Looking to survive in a world taken over by zombies, a dorky college student teams with an urban roughneck and a pair of grifter sisters.']
 ['s8806' 'Movie' 'Zoom' ... '88 min'
  'Children & Family Movies, Comedies'
  'Dragged from civilian life, a former superhero must train a new crop of youthful saviors when the military preps for an attack by a familiar villain.']
 ['s8807' 'Movie' 'Zubaan' ... '111 min'
  'Dramas, International Movies, Music & Musicals'
  "A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past."]]


------------------------------------


Do you want to generate a detailed report on the exploration of your dataset?
[y/n]: y
Generating report...

TypeError: ignored

In [ ]:
import pandas as pd
import numpy as np
import missingno as msno
import seaborn as sns
import math
import re
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
from plotly.offline import init_notebook_mode, iplot
from wordcloud import WordCloud, STOPWORDS
import requests
from lxml import html
init_notebook_mode(connected=True)
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None

data = pd.read_csv('netflix_titles.csv')

data['listed_in']


l1 = []
for value in data['listed_in']:
  l1.append(value.split(','))

# sns.set(style='white')

# plt.figure(figsize=(15, 8))
# plt.title('Count of movie Genres', size=20)
# genres = data['listed_in'].value_counts()
# ax = sns.barplot(x=genres.values, y=genres.index, palette='coolwarm')
# plt.xlabel('Genre', size=15)
# plt.ylabel('Count', size=15)
# for i, v in enumerate(genres.values):
#     plt.text(x=40, y=i+0.12, s=v, color='k', fontsize=12.5)
# plt.show()

In [ ]:
import pandas as pd
# import numpy as np
# import missingno as msno
# import seaborn as sns
# import math
# import re
# import matplotlib.pyplot as plt
# import plotly.graph_objects as go
# import plotly.express as px
# from plotly.offline import init_notebook_mode, iplot
# from wordcloud import WordCloud, STOPWORDS
# import requests
# from lxml import html
# init_notebook_mode(connected=True)
# pd.set_option('display.max_columns', None)
# pd.options.mode.chained_assignment = None

data = pd.read_csv('netflix_titles.csv')

data['listed_in']


l1 = []
for value in data['listed_in']:
  l1.append(value.split(','))

In [ ]:
! pip install xplore

from xplore.data import xplore

import pandas as pd

data = pd.read_csv('disney_plus_titles.csv')





xplore(data)

Collecting xplore
  Downloading xplore-0.0.1.tar.gz (5.2 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from xplore) (1.3.5)
Requirement already satisfied: pandas_profiling in /usr/local/lib/python3.7/dist-packages (from xplore) (1.4.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->xplore) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->xplore) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->xplore) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->xplore) (1.15.0)
Requirement already satisfied: matplotlib>=1.4 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling->xplore) (3.2.2)
Requirement already satisfied: jinja2>=2.8 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling->xplore) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.8->pandas_profiling->xplore) (2.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.4->pandas_profiling->xplore) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.4->pandas_profiling->xplore) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.4->pandas_profiling->xplore) (3.0.8)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=1.4->pandas_profiling->xplore) (4.1.1)
Building wheels for collected packages: xplore
  Building wheel for xplore (setup.py) ... done
  Created wheel for xplore: filename=xplore-0.0.1-py3-none-any.whl size=4195 sha256=6ba3dd9722b04c4a0f243cde085a01da4ce3e6126eeac23f5cfd6ea3052aeaba
  Stored in directory: /root/.cache/pip/wheels/8f/ee/9f/dc64edd7cbc7d72291f309afa83bcb8258ada61b2445a7b2cf
Successfully built xplore
Installing collected packages: xplore
Successfully installed xplore-0.0.1
------------------------------------
The fist 5 entries of your dataset are:

  show_id     type                                             title  \
0      s1    Movie  Duck the Halls: A Mickey Mouse Christmas Special
1      s2    Movie                            Ernest Saves Christmas
2      s3    Movie                      Ice Age: A Mammoth Christmas
3      s4    Movie                        The Queen Family Singalong
4      s5  TV Show                             The Beatles: Get Back

                            director  \
0  Alonso Ramirez Ramos, Dave Wasson
1                        John Cherry
2                       Karen Disher
3                    Hamish Hamilton
4                                NaN

                                                cast        country  \
0  Chris Diamantopoulos, Tony Anselmo, Tress MacN...            NaN
1           Jim Varney, Noelle Parker, Douglas Seale            NaN
2  Raymond Albert Romano, John Leguizamo, Denis L...  United States
3  Darren Criss, Adam Lambert, Derek Hough, Alexa...            NaN
4  John Lennon, Paul McCartney, George Harrison, ...            NaN

          date_added  release_year rating  duration  \
0  November 26, 2021          2016   TV-G    23 min
1  November 26, 2021          1988     PG    91 min
2  November 26, 2021          2011   TV-G    23 min
3  November 26, 2021          2021  TV-PG    41 min
4  November 25, 2021          2021    NaN  1 Season

                       listed_in  \
0              Animation, Family
1                         Comedy
2      Animation, Comedy, Family
3                        Musical
4  Docuseries, Historical, Music

                                         description
0   Join Mickey and the gang as they duck the halls!
1  Santa Claus passes his magic bag to a new St. ...
2          Sid the Sloth is on Santa's naughty list.
3               This is real life, not just fantasy!
4  A three-part documentary from Peter Jackson ca...


------------------------------------
The last 5 entries of your dataset are:

     show_id   type                                           title  \
1445   s1446  Movie                        X-Men Origins: Wolverine
1446   s1447  Movie  Night at the Museum: Battle of the Smithsonian
1447   s1448  Movie                                 Eddie the Eagle
1448   s1449  Movie                            Bend It Like Beckham
1449   s1450  Movie           Captain Sparky vs. The Flying Saucers

             director                                               cast  \
1445       Gavin Hood  Hugh Jackman, Liev Schreiber, Danny Huston, wi...
1446       Shawn Levy  Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...
1447  Dexter Fletcher  Tom Costello, Jo Hartley, Keith Allen, Dickon ...
1448  Gurinder Chadha  Parminder Nagra, Keira Knightley, Jonathan Rhy...
1449      Mark Waring                                      Charlie Tahan

                                     country          date_added  \
1445           United States, United Kingdom        June 4, 2021
1446                   United States, Canada       April 2, 2021
1447  United Kingdom, Germany, United States   December 18, 2020
1448  United Kingdom, Germany, United States  September 18, 2020
1449                           United States       April 1, 2020

      release_year rating duration  \
1445          2009  PG-13  108 min
1446          2009     PG  106 min
1447          2016  PG-13  107 min
1448          2003  PG-13  112 min
1449          2012   TV-G    2 min

                                          listed_in  \
1445      Action-Adventure, Family, Science Fiction
1446               Action-Adventure, Comedy, Family
1447                    Biographical, Comedy, Drama
1448                   Buddy, Comedy, Coming of Age
1449  Action-Adventure, Animals & Nature, Animation

                                            description
1445  Wolverine unites with legendary X-Men to fight...
1446  Larry Daley returns to rescue some old friends...
1447  True story of Eddie Edwards, a British ski-jum...
1448  Despite the wishes of their traditional famili...
1449         View one of Sparky's favorite home movies.


------------------------------------
Stats on your dataset:

<bound method NDFrame.describe of      show_id     type                                             title  \
0         s1    Movie  Duck the Halls: A Mickey Mouse Christmas Special
1         s2    Movie                            Ernest Saves Christmas
2         s3    Movie                      Ice Age: A Mammoth Christmas
3         s4    Movie                        The Queen Family Singalong
4         s5  TV Show                             The Beatles: Get Back
...      ...      ...                                               ...
1445   s1446    Movie                          X-Men Origins: Wolverine
1446   s1447    Movie    Night at the Museum: Battle of the Smithsonian
1447   s1448    Movie                                   Eddie the Eagle
1448   s1449    Movie                              Bend It Like Beckham
1449   s1450    Movie             Captain Sparky vs. The Flying Saucers

                               director  \
0     Alonso Ramirez Ramos, Dave Wasson
1                           John Cherry
2                          Karen Disher
3                       Hamish Hamilton
4                                   NaN
...                                 ...
1445                         Gavin Hood
1446                         Shawn Levy
1447                    Dexter Fletcher
1448                    Gurinder Chadha
1449                        Mark Waring

                                                   cast  \
0     Chris Diamantopoulos, Tony Anselmo, Tress MacN...
1              Jim Varney, Noelle Parker, Douglas Seale
2     Raymond Albert Romano, John Leguizamo, Denis L...
3     Darren Criss, Adam Lambert, Derek Hough, Alexa...
4     John Lennon, Paul McCartney, George Harrison, ...
...                                                 ...
1445  Hugh Jackman, Liev Schreiber, Danny Huston, wi...
1446  Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...
1447  Tom Costello, Jo Hartley, Keith Allen, Dickon ...
1448  Parminder Nagra, Keira Knightley, Jonathan Rhy...
1449                                      Charlie Tahan

                                     country          date_added  \
0                                        NaN   November 26, 2021
1                                        NaN   November 26, 2021
2                              United States   November 26, 2021
3                                        NaN   November 26, 2021
4                                        NaN   November 25, 2021
...                                      ...                 ...
1445           United States, United Kingdom        June 4, 2021
1446                   United States, Canada       April 2, 2021
1447  United Kingdom, Germany, United States   December 18, 2020
1448  United Kingdom, Germany, United States  September 18, 2020
1449                           United States       April 1, 2020

      release_year rating  duration  \
0             2016   TV-G    23 min
1             1988     PG    91 min
2             2011   TV-G    23 min
3             2021  TV-PG    41 min
4             2021    NaN  1 Season
...            ...    ...       ...
1445          2009  PG-13   108 min
1446          2009     PG   106 min
1447          2016  PG-13   107 min
1448          2003  PG-13   112 min
1449          2012   TV-G     2 min

                                          listed_in  \
0                                 Animation, Family
1                                            Comedy
2                         Animation, Comedy, Family
3                                           Musical
4                     Docuseries, Historical, Music
...                                             ...
1445      Action-Adventure, Family, Science Fiction
1446               Action-Adventure, Comedy, Family
1447                    Biographical, Comedy, Drama
1448                   Buddy, Comedy, Coming of Age
1449  Action-Adventure, Animals & Nature, Animation

                                            description
0      Join Mickey and the gang as they duck the halls!
1     Santa Claus passes his magic bag to a new St. ...
2             Sid the Sloth is on Santa's naughty list.
3                  This is real life, not just fantasy!
4     A three-part documentary from Peter Jackson ca...
...                                                 ...
1445  Wolverine unites with legendary X-Men to fight...
1446  Larry Daley returns to rescue some old friends...
1447  True story of Eddie Edwards, a British ski-jum...
1448  Despite the wishes of their traditional famili...
1449         View one of Sparky's favorite home movies.

[1450 rows x 12 columns]>


------------------------------------
The Value types of each column are:

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object


------------------------------------
Info on your Dataset:

<bound method DataFrame.info of      show_id     type                                             title  \
0         s1    Movie  Duck the Halls: A Mickey Mouse Christmas Special
1         s2    Movie                            Ernest Saves Christmas
2         s3    Movie                      Ice Age: A Mammoth Christmas
3         s4    Movie                        The Queen Family Singalong
4         s5  TV Show                             The Beatles: Get Back
...      ...      ...                                               ...
1445   s1446    Movie                          X-Men Origins: Wolverine
1446   s1447    Movie    Night at the Museum: Battle of the Smithsonian
1447   s1448    Movie                                   Eddie the Eagle
1448   s1449    Movie                              Bend It Like Beckham
1449   s1450    Movie             Captain Sparky vs. The Flying Saucers

                               director  \
0     Alonso Ramirez Ramos, Dave Wasson
1                           John Cherry
2                          Karen Disher
3                       Hamish Hamilton
4                                   NaN
...                                 ...
1445                         Gavin Hood
1446                         Shawn Levy
1447                    Dexter Fletcher
1448                    Gurinder Chadha
1449                        Mark Waring

                                                   cast  \
0     Chris Diamantopoulos, Tony Anselmo, Tress MacN...
1              Jim Varney, Noelle Parker, Douglas Seale
2     Raymond Albert Romano, John Leguizamo, Denis L...
3     Darren Criss, Adam Lambert, Derek Hough, Alexa...
4     John Lennon, Paul McCartney, George Harrison, ...
...                                                 ...
1445  Hugh Jackman, Liev Schreiber, Danny Huston, wi...
1446  Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...
1447  Tom Costello, Jo Hartley, Keith Allen, Dickon ...
1448  Parminder Nagra, Keira Knightley, Jonathan Rhy...
1449                                      Charlie Tahan

                                     country          date_added  \
0                                        NaN   November 26, 2021
1                                        NaN   November 26, 2021
2                              United States   November 26, 2021
3                                        NaN   November 26, 2021
4                                        NaN   November 25, 2021
...                                      ...                 ...
1445           United States, United Kingdom        June 4, 2021
1446                   United States, Canada       April 2, 2021
1447  United Kingdom, Germany, United States   December 18, 2020
1448  United Kingdom, Germany, United States  September 18, 2020
1449                           United States       April 1, 2020

      release_year rating  duration  \
0             2016   TV-G    23 min
1             1988     PG    91 min
2             2011   TV-G    23 min
3             2021  TV-PG    41 min
4             2021    NaN  1 Season
...            ...    ...       ...
1445          2009  PG-13   108 min
1446          2009     PG   106 min
1447          2016  PG-13   107 min
1448          2003  PG-13   112 min
1449          2012   TV-G     2 min

                                          listed_in  \
0                                 Animation, Family
1                                            Comedy
2                         Animation, Comedy, Family
3                                           Musical
4                     Docuseries, Historical, Music
...                                             ...
1445      Action-Adventure, Family, Science Fiction
1446               Action-Adventure, Comedy, Family
1447                    Biographical, Comedy, Drama
1448                   Buddy, Comedy, Coming of Age
1449  Action-Adventure, Animals & Nature, Animation

                                            description
0      Join Mickey and the gang as they duck the halls!
1     Santa Claus passes his magic bag to a new St. ...
2             Sid the Sloth is on Santa's naughty list.
3                  This is real life, not just fantasy!
4     A three-part documentary from Peter Jackson ca...
...                                                 ...
1445  Wolverine unites with legendary X-Men to fight...
1446  Larry Daley returns to rescue some old friends...
1447  True story of Eddie Edwards, a British ski-jum...
1448  Despite the wishes of their traditional famili...
1449         View one of Sparky's favorite home movies.

[1450 rows x 12 columns]>


------------------------------------
The shape of your dataset in the order of rows and columns is:

(1450, 12)


------------------------------------
The features of your dataset are:

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')


------------------------------------
The total number of null values from individual columns of your data set are:

show_id           0
type              0
title             0
director        473
cast            190
country         219
date_added        3
release_year      0
rating            3
duration          0
listed_in         0
description       0
dtype: int64


------------------------------------
The number of rows in your dataset are:

1450


------------------------------------
The values in your dataset are:

[['s1' 'Movie' 'Duck the Halls: A Mickey Mouse Christmas Special' ...
  '23 min' 'Animation, Family'
  'Join Mickey and the gang as they duck the halls!']
 ['s2' 'Movie' 'Ernest Saves Christmas' ... '91 min' 'Comedy'
  'Santa Claus passes his magic bag to a new St. Nic.']
 ['s3' 'Movie' 'Ice Age: A Mammoth Christmas' ... '23 min'
  'Animation, Comedy, Family' "Sid the Sloth is on Santa's naughty list."]
 ...
 ['s1448' 'Movie' 'Eddie the Eagle' ... '107 min'
  'Biographical, Comedy, Drama'
  'True story of Eddie Edwards, a British ski-jumper whose Olympic performance wins the hearts of fans.']
 ['s1449' 'Movie' 'Bend It Like Beckham' ... '112 min'
  'Buddy, Comedy, Coming of Age'
  'Despite the wishes of their traditional families, two girls aim for careers in professional soccer.']
 ['s1450' 'Movie' 'Captain Sparky vs. The Flying Saucers' ... '2 min'
  'Action-Adventure, Animals & Nature, Animation'
  "View one of Sparky's favorite home movies."]]


------------------------------------


Do you want to generate a detailed report on the exploration of your dataset?
[y/n]: y
Generating report...

TypeError: ignored

In [ ]:
import pandas as pd

data = pd.read_csv('netflix_titles.csv')

# data.loc[0:, "country"]

data.describe().release_year

count    8807.000000
mean     2014.180198
std         8.819312
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2019.000000
max      2021.000000
Name: release_year, dtype: float64

# OVERARCHING QUESTIONS

QUESTIONS ON DATASET

Understanding what content is available in different countries

Identifying similar content by matching text-based features

Network analysis of Actors / Directors and find interesting insights

Does Disney+ has more focus on TV Shows than movies in recent years.

# FOR META EDA

Are there notable differences by country?

● What genres have gotten more or less popular?
- Use the most_common() and correlate it with time

● Is Netflix investing more in TV shows or movies? 
- Calculate wheter TV or Movies are being made more

What trends are there in the length of movies or the number of seasons of TV shows?

● Are there certain actors or directors that Netflix seems to like?

In Data cleansisng, how do we save the new data?
- Be sure to remove NULL